- Avocado/src/components/pages/UserAcct.jsx
Added a form skeleton, working on getting state to work
> Updates to userAccount

- Avocado/src/App.jsx
- Avocado/src/components/pages/AdminMenu.jsx
- Avocado/src/components/pages/AdminRestaurant.jsx
- Avocado/src/components/pages/Login.jsx
- Avocado/src/components/pages/Signup.jsx
Created Signup.jsx file, copy/pasted code from login. Added the ability to create a customer or an owner based on the user's choice from a dropdown menu.
Added skeletons of forms to adminMenu and adminRestaurant.
> added owner signup to signup.jsx

- Avocado/src/components/pages/Signup.jsx
Added in styles according to Peter's style guide
> css edits to signup.jsx

- Avocado/src/components/pages/AdminRestaurant.jsx
- Avocado/src/components/partials/AdminNavBar.jsx
Fixed adminnav to stay a fixed width on larger screens; moved get route from adminrestaurant to backend
> fixed bug on adminnav, moved route to backend

- Avocado/index.html
- Avocado/src/components/pages/AdminRestaurant.jsx
- Avocado/src/components/partials/RestaurantCard.jsx
also working on ability to add logo when you add a restaurant; need the loggedin user's id before it'll work i think
> css edits to adminrestaurant

- Avocado/src/components/pages/AdminRestaurant.jsx
- Avocado/src/components/partials/RestaurantCard.jsx
discovered an improvement to be made: once admin adds a restaurant, they have to refresh the page to see their new restaurant. Looking into useEffect and other hooks to see what can be done to re-render on change
> more css edits to adminRest and restCard

- Avocado/package-lock.json
- Avocado/package.json
- Avocado/src/components/Layout/RestaurantAdmin.jsx
installed a new package, ended up not using it and deleting it.
The user can upload a logo when using the bottom form; next step is to get that working in the main form, or leaving that off for the update restaurant modal.
> edits to restaurant admin

- Avocado/src/components/Layout/RestaurantAdmin.jsx
- Avocado/src/components/partials/AdminNavBar.jsx
updated link to restaurantadmin on navbar, added restaurant id to state when user clicks on a restaurant
> edits to restaurantadmin and navbar

- Avocado/src/components/pages/Admin/ManageRestaurants.jsx
- Avocado/src/components/pages/Admin/UpdateRestaurant.jsx
can get the current restaurant's name in the input, but it's set in state so it's not able to be edited
> still working on update route

- Avocado/src/components/pages/Admin/ManageRestaurants.css
- Avocado/src/components/pages/Admin/ManageRestaurants.jsx
- Avocado/src/components/pages/Admin/UpdateRestaurant.jsx
- Avocado/src/components/pages/Admin/UpdateRestaurantOptions.jsx
working on update; got it working nicely so far, next step is logo
> functionality edits to managerestaurants and children

- Avocado/package-lock.json
- Avocado/package.json
- Avocado/src/components/Layout/DashboardSignup.jsx
- Avocado/src/components/Layout/RestaurantDashboard.jsx
- Avocado/src/components/pages/Admin/ManageRestaurants.jsx
- Avocado/src/components/pages/Admin/Menu/RestaurantAddMenuItemForm.jsx
- Avocado/src/components/pages/Admin/Menu/RestaurantMenu.jsx
- Avocado/src/components/pages/Admin/RestaurantCard.jsx
- Avocado/src/components/pages/Admin/UpdateRestaurant.jsx
- Avocado/src/components/pages/Admin/UpdateRestaurantOptions.jsx
- Avocado/src/components/pages/UserAcct.jsx
- Avocado/src/components/partials/AdminNavBar.jsx
users can upload an image for the logo to supabase storage, which also sends the url path to the restaurant table where it can be rendered on the screen.
fixed bug on navbar where it is open by default
installed toastify
> css/functionality edits to Admin Restaurant files

- Avocado/.gitignore
- Avocado/src/components/pages/Admin/ManageRestaurants.jsx
manage restaurant routes now go to render
> added env file to gitignore, updated routes

- Avocado/src/components/pages/Admin/Menu/RestaurantAddMenuItemForm.jsx
- Avocado/src/components/pages/Admin/Menu/UpdateMenuItem.jsx
-added select and options
-adjusted modal layout
-broke modal - click off no longer working
-added autofill for update form modal
> Update and Add Item Forms

- Avocado/src/components/pages/Admin/UpdateRestaurant.jsx
Admins can now delete a restaurant and it will delete all menu items associated with that restaurant
> Added delete functionality to restaurant pages

- Avocado/src/components/pages/Admin/Menu/RestaurantAddMenuItemForm.jsx
- Avocado/src/components/pages/Admin/Menu/RestaurantMenu.jsx
- Avocado/src/components/pages/Admin/Menu/RestaurantMenuItemCard.jsx
- Avocado/src/components/pages/Admin/Menu/UpdateMenuItem.jsx
- Avocado/src/components/partials/AdminNavBar.jsx
- Avocado/src/components/partials/AdminNavBarLinks.jsx
working on mobile responsiveness; need to work on modal next
> Responsiveness edits to AdminNav, ResMenu

- Avocado/package-lock.json
- Avocado/package.json
- Avocado/src/components/Layout/Reports.jsx
> Meg div frontend branch1

- Avocado/src/components/pages/Admin/ManageRestaurants/AddRestaurantForm.jsx
- Avocado/src/components/pages/Admin/ManageRestaurants/ManageRestaurants.jsx
- Avocado/src/components/pages/Admin/ManageRestaurants/RestaurantCard.jsx
- Avocado/src/components/pages/Admin/ManageRestaurants/UpdateRestaurantModal.jsx
- Avocado/src/components/pages/Admin/Menu/RestaurantAddMenuItemForm.jsx
- Avocado/src/components/pages/Admin/Menu/UpdateMenuItem.jsx
Cleaned commented-out code and unused imports/variables from manage restaurants folder
> Cleaned up code a bit more

- Avocado/src/components/pages/Admin/ManageRestaurants/ManageRestaurants.jsx
- Avocado/src/components/pages/Admin/ManageRestaurants/UpdateRestaurantModal.jsx
- Avocado/src/components/pages/Admin/Menu/RestaurantAddMenuItemForm.jsx
- Avocado/src/components/pages/Admin/Menu/RestaurantMenu.jsx
- Avocado/src/components/pages/Admin/Menu/RestaurantMenuItemCard.jsx
- Avocado/src/components/pages/Admin/Menu/UpdateMenuItem.jsx
Now if an item is added or updated, it will re-render to show the addition/changes
> Put toggles in menuItems pages

- Avocado/src/components/Layout/CustomerDashboard.jsx
- Avocado/src/components/Layout/CustomerRestaurantCard.jsx
- Avocado/src/components/pages/Admin/ManageRestaurants/RestaurantCard.jsx
- Avocado/src/components/partials/AdminNavBar.jsx
- Avocado/src/components/partials/CustomerNavBar.jsx
- Avocado/src/components/partials/CustomerNavBarLinks.jsx
- Avocado/src/components/partials/MenuItem.jsx
icons added to customer nav, made customer dashboard mobile responsive
> styling added to customer dashboard

- Avocado/src/components/Layout/CustomerRestaurantCard.jsx
- Avocado/src/components/pages/Customer/Menu.jsx
- Avocado/src/components/partials/Cart.jsx
- Avocado/src/components/partials/CartItem.jsx
- Avocado/src/components/partials/CustomerNavBar.jsx
- Avocado/src/components/partials/CustomerNavBarLinks.jsx
- Avocado/src/components/partials/MenuItem.jsx
Added counter for smaller screens and for num of items in cart on larger screens. Doesn't persist. Put clearcart function in useEffect so the cart is cleared when the page refreshes. A little clunky, but otherwise customers can have items in their cart from multiple restaurants. Might have to change/figure something else out once we get checkout working.
> Styling cart

- Avocado/src/components/pages/Customer/Menu.jsx
- Avocado/src/components/partials/Cart.jsx
- Avocado/src/components/partials/MenuItem.jsx
- Avocado/src/components/partials/MenuItemModal.jsx
Got the modal to pop out when you click on a menu item; there, you can see the full description of the item and add it to your cart.
> More cart edits

- Avocado/src/components/pages/Customer/Menu.jsx
- Avocado/src/components/partials/MenuItem.jsx
- Avocado/src/components/partials/MenuItemModal.jsx
mobile responsive, just need to make the cart on mobile sizes a modal that pops up when you click the cart button
> more edits to cart

- Avocado/src/components/pages/Admin/AdminAccount.jsx
- Avocado/src/components/pages/Customer/CustomerAccount.jsx
- Avocado/src/components/pages/Customer/DeleteCustomerForm.jsx
added toggle/supabase call/toastify so when a user updates their account it'll re-fetch their details from supabase and re-render the page. Delete account still doesn't redirect to login, even after adding the signout() function
> updates to functionality of account pages

- Avocado/src/components/Layout/Button.jsx
- Avocado/src/components/Layout/Reports.jsx
- Avocado/src/components/pages/Admin/AdminAccount.jsx
- Avocado/src/components/pages/Admin/DeleteAdminForm.jsx
- Avocado/src/components/pages/Admin/ReportsRestaurantOptions.jsx
Can't get it perfect, not sure exactly what Plotly is doing. Looks better on larger screens
> CSS edits to reports

- Avocado/src/components/Layout/RestaurantDashboard.jsx
- Avocado/src/components/partials/AdminNavBar.jsx
Edited size of photo, added link to dashboard on logo in nav
> CSS edits to nav, restaurant dash

- Avocado/src/components/pages/Customer/OrderConfirm.jsx
This reverts commit c0cde270f93bf6d167ab0ad73628c2962e5f484b, reversing changes made to e69e00d3e05342bce3c08309b9f2001c1f10391f.
> Revert "Merge pull request #220 from Lasseignejk/Peter-2"

- Avocado/src/components/Layout/DashboardLogin.jsx
If login credentials are wrong, toast will tell you so.
> added toastify to login

- Avocado/src/components/Layout/DashboardSignup.jsx
won't let person sign up if they are missing information
> added toastify to sign up

- Avocado/src/components/Layout/Reports.jsx
> updated the table graph on reports page
